@startuml
'https://plantuml.com/class-diagram
skinparam handwritten true
class client{}
class SimpleFactory{
 + {Static} getProduct(String): Product
}
note top of SimpleFactory
Role - SimpleFactrory
 -provide a static method to get
  instance of Product subclass
end note
class Product{}
note top of Product
Role - Product
 -Objects of this Class & it's
  subclasses are needed
end note
class ProductA{}
class ProductB{}

client->SimpleFactory
SimpleFactory -> Product
Product -D-> ProductA
Product -D-> ProductB


@enduml